const appState={page:"home",routeState:{},workspace:null,lastRefresh:null};
const pages={
home:["Your strategic intelligence workspace","Create governed research campaigns, review evidence, monitor trust, and move from signal to decision."],
discover:["Start a governed discovery","Turn a topic, company, market, or weak signal into a controlled intelligence workflow."],
campaigns:["Campaign command","Track recurring intelligence campaigns, refresh cycles, results, blockers, and next actions."],
workspace:["Workspace memory","Continue saved discoveries, campaign drafts, recent activity, and intelligence timelines."],
evidence:["Evidence review","Review source-backed claims, confidence, gaps, and what Claire still needs before recommendation."],
trust:["Source trust","Understand source reputation, adaptive weighting, quarantine, and release conditions."],
portfolio:["Portfolio intelligence","Translate trend and evidence signals into watchlists, strategic baskets, and action candidates."],
launch:["Launch center","Separate installed readiness from actual live-use readiness, with visible blockers."],
system:["System health","Runtime health, route wiring, manifests, deployment protection, and recovery visibility."]};
const routes={health:["/health","/"],dashboard:["/dashboard/state","/api/dashboard/state"],internet:["/internet/ops/dashboard","/internet/operations/dashboard"],campaigns:["/internet/campaigns","/api/internet/campaigns"],sourceTrust:["/internet/source-trust","/api/internet/source-trust"],launchLock:["/launch/regression-lock","/api/launch/regression-lock"]};
function node(t,a={},c=[]){const n=document.createElement(t);Object.entries(a).forEach(([k,v])=>{if(k==="class")n.className=v;else if(k==="text")n.textContent=v;else n.setAttribute(k,v)});c.forEach(x=>n.append(x));return n}
async function firstReachable(paths){for(const p of paths){try{const r=await fetch(p,{cache:"no-store"});if(r.ok)return{ok:true,path:p,status:r.status}}catch(e){}}return{ok:false,path:null,status:null}}
async function refreshState(){const e=await Promise.all(Object.entries(routes).map(async([k,p])=>[k,await firstReachable(p)]));appState.routeState=Object.fromEntries(e);appState.workspace=ClaireWorkspace.load();appState.lastRefresh=new Date()}
function badge(ok,yes="Ready",no="Needs wiring"){return node("span",{class:"badge "+(ok?"good":"warn"),text:ok?yes:no})}
function card(title,children,cls=""){return node("section",{class:"card "+cls},[node("h2",{text:title}),...(Array.isArray(children)?children:[children])])}
function kpi(label,value){return node("div",{class:"kpi"},[node("span",{text:label}),typeof value==="string"?node("strong",{text:value}):value])}
function renderReadiness(){const rs=appState.routeState;const w=appState.workspace||{};const items=[["Runtime",rs.health?.ok?"Online":"Unavailable"],["Internet",rs.internet?.ok?"Connected":"Needs wiring"],["Workspace",(w.activity||[]).length+" events"],["Drafts",(w.drafts||[]).length+" saved"]];const root=document.getElementById("readiness");root.innerHTML="";items.forEach(([l,v])=>root.append(node("div",{class:"readiness-card"},[node("span",{text:l}),node("strong",{text:v})])))}
function step(title,text,target){const s=node("button",{class:"step",type:"button"},[node("strong",{text:title}),node("small",{text})]);s.addEventListener("click",()=>setPage(target));return s}
function home(){const w=appState.workspace||{activity:[],drafts:[]};return[card("Continue where you left off",node("div",{class:"workflow"},[step("Discover","Start or continue a strategic investigation.","discover"),step("Workspace","Open saved briefs, drafts, and activity.","workspace"),step("Campaigns","Prepare a recurring governed campaign.","campaigns"),step("Evidence","Review confidence, gaps, and support.","evidence"),step("Launch","Confirm readiness before live use.","launch")]),"full glow"),card("Workspace continuity",[kpi("Saved drafts",String((w.drafts||[]).length)),kpi("Recent activity",String((w.activity||[]).length)),kpi("Timeline events",String((w.timeline||[]).length)),kpi("Last opened",w.lastOpenedAt?new Date(w.lastOpenedAt).toLocaleString():"First use")],"wide"),card("Next best step",node("p",{text:"Create one discovery brief, save it, then confirm it appears in Workspace Memory before wiring live campaign execution."}))]}
function field(label,type,opts,id){const w=node("div",{class:"field"},[node("label",{text:label})]);if(type==="textarea")w.append(node("textarea",{placeholder:opts,id}));else if(type==="select"){const s=node("select",{id});opts.forEach(o=>s.append(node("option",{text:o})));w.append(s)}else w.append(node("input",{placeholder:opts||"",id}));return w}
function action(text,handler,primary=true){const b=node("button",{class:"btn "+(primary?"primary":"secondary"),type:"button",text});b.addEventListener("click",handler);return b}
function disabledAction(text,reason){const b=node("button",{class:"btn secondary",type:"button",title:reason,text});b.disabled=true;b.style.opacity=".55";return b}
function discover(){return[card("Create a discovery brief",node("div",{class:"form-grid"},[field("What should Claire investigate?","textarea","Example: emerging companies using AI for grid optimization","disc_question"),field("Domain","select",["Markets","Technology","Portfolio","Competitors","Regulation","Acquisition Targets"],"disc_domain"),field("Time horizon","select",["Now","30 days","90 days","6 months","12 months"],"disc_horizon"),node("div",{class:"action-row"},[action("Save discovery draft",()=>{const q=document.getElementById("disc_question").value.trim();const d=document.getElementById("disc_domain").value;const h=document.getElementById("disc_horizon").value;appState.workspace=ClaireWorkspace.saveDiscovery({title:q.slice(0,70)||"Strategic discovery",question:q,domain:d,horizon:h});setPage("workspace")}),disabledAction("Start governed discovery","Backend action schema not confirmed yet")])]),"wide"),card("Governance preview",[kpi("Bounded execution",node("span",{class:"badge good",text:"Required"})),kpi("Evidence required",node("span",{class:"badge good",text:"Required"})),kpi("Fake success allowed",node("span",{class:"badge bad",text:"Never"}))])]}
function item(t,x){return node("div",{class:"item"},[node("strong",{text:t}),node("p",{text:x})])}
function workspace(){const w=appState.workspace||ClaireWorkspace.load();const drafts=(w.drafts||[]);const acts=(w.activity||[]);return[card("Saved work",drafts.length?node("div",{class:"list"},drafts.slice(0,8).map(d=>item(d.title||"Untitled",`${d.status||"draft"} • ${d.domain||d.cadence||"General"} • ${new Date(d.createdAt).toLocaleString()}`))):node("div",{class:"empty"},[node("h3",{text:"No saved work yet"}),node("p",{text:"Save a discovery or campaign draft and it will appear here."})]),"wide"),card("Recent activity",acts.length?node("div",{class:"list"},acts.slice(0,8).map(a=>item(a.title,a.detail+" • "+new Date(a.createdAt).toLocaleString()))):node("div",{class:"empty"},[node("h3",{text:"No activity yet"}),node("p",{text:"Your workspace timeline starts once you save a draft or activity."})])),card("Workspace controls",node("div",{class:"action-row"},[action("Add note",()=>{appState.workspace=ClaireWorkspace.addActivity(ClaireWorkspace.load(),"operator_note","Operator note","Manual note added from dashboard.");setPage("workspace")},false),action("Clear local workspace",()=>{if(confirm("Clear local Claire workspace memory for this browser?")){appState.workspace=ClaireWorkspace.clearWorkspace();setPage("workspace")}},false)]),"full")]}
function campaigns(){return[card("Campaign draft setup",node("div",{class:"form-grid"},[field("Campaign objective","textarea","Track AI grid optimization companies weekly","camp_objective"),field("Cadence","select",["Manual","Daily","Weekly","Monthly"],"camp_cadence"),node("div",{class:"action-row"},[action("Save campaign draft",()=>{const obj=document.getElementById("camp_objective").value.trim();const cad=document.getElementById("camp_cadence").value;appState.workspace=ClaireWorkspace.saveCampaignDraft({title:obj.slice(0,70)||"Governed campaign",objective:obj,cadence:cad});setPage("workspace")}),disabledAction("Activate live campaign","Backend live activation route not confirmed yet")])]),"wide"),card("Campaign route",[kpi("Backend",badge(appState.routeState.campaigns?.ok,"Reachable","Missing")),kpi("Refresh cycles",node("span",{class:"badge warn",text:"Awaiting live data"})),kpi("Persistence",node("span",{class:"badge good",text:"Local drafts active"}))])]}
function evidence(){return[card("Evidence inbox",node("div",{class:"list"},[item("Evidence baskets","Claims should be grouped by source, confidence, date, and supporting route."),item("Open questions","Claire should make uncertainty visible instead of burying it in raw JSON."),item("Decision threshold","Evidence should be marked insufficient, emerging, actionable, or blocked.")]),"wide"),card("Current evidence state",[kpi("Claims","Not loaded"),kpi("Gaps","Visible after run"),kpi("Confidence",node("span",{class:"badge warn",text:"Unknown"}))])]}
function trust(){return[card("Trust center",[kpi("Source trust route",badge(appState.routeState.sourceTrust?.ok,"Reachable","Missing")),kpi("Quarantine",node("span",{class:"badge warn",text:"No live state"})),kpi("Reputation memory",node("span",{class:"badge warn",text:"No live state"}))],"wide"),card("User-facing trust rule",node("p",{text:"Before Claire recommends an action, the dashboard should show which sources were trusted, discounted, quarantined, or unresolved."}))]}
function portfolio(){return[card("Portfolio intelligence",node("div",{class:"empty"},[node("h3",{text:"No portfolio view generated yet"}),node("p",{text:"This surface should convert trends and evidence into watchlists, risk notes, opportunity baskets, and monitored assumptions."})]),"wide"),card("Output types",node("div",{class:"list"},[item("Watchlist","Companies, markets, technologies, and signals worth monitoring."),item("Opportunity basket","Grouped thesis candidates with confidence and evidence depth."),item("Risk register","Known uncertainty, weak sources, and governance blockers.")]))]}
function launch(){return[card("Launch readiness is not the same as installed",[kpi("Install stack",node("span",{class:"badge good",text:"Built through v17.54"})),kpi("Regression lock",badge(appState.routeState.launchLock?.ok,"Route found","Needs route")),kpi("Real user-active proof",node("span",{class:"badge warn",text:"Still pending"})),kpi("Workspace continuity",node("span",{class:"badge good",text:"Local persistence active"}))],"wide"),card("Before real launch",node("div",{class:"list"},[item("Use the dashboard","Run at least one full user workflow from discovery to evidence review."),item("Verify outputs","Confirm files, campaign state, and dashboard rendering match."),item("Record blockers","Any unavailable route or dead button is a launch blocker, not cosmetic polish.")]))]}
function system(){return[card("Route wiring",[kpi("/health",badge(appState.routeState.health?.ok,"Reachable","Missing")),kpi("/dashboard/state",badge(appState.routeState.dashboard?.ok,"Reachable","Missing")),kpi("/internet/ops/dashboard",badge(appState.routeState.internet?.ok,"Reachable","Missing")),kpi("/internet/campaigns",badge(appState.routeState.campaigns?.ok,"Reachable","Missing")),kpi("/internet/source-trust",badge(appState.routeState.sourceTrust?.ok,"Reachable","Missing")),kpi("/launch/regression-lock",badge(appState.routeState.launchLock?.ok,"Reachable","Missing"))],"wide"),card("System principle",node("p",{text:"This page is allowed to be technical. The rest of the product should remain user-facing and decision-oriented."}))]}
const renderers={home,discover,campaigns,workspace,evidence,trust,portfolio,launch,system};
function setPage(page){appState.page=page;document.querySelectorAll(".nav-link").forEach(b=>b.classList.toggle("active",b.dataset.page===page));const meta=pages[page];document.getElementById("page-title").textContent=meta[0];document.getElementById("page-subtitle").textContent=meta[1];renderReadiness();const c=document.getElementById("content");c.innerHTML="";renderers[page]().forEach(x=>c.append(x))}
document.querySelectorAll(".nav-link").forEach(b=>b.addEventListener("click",()=>setPage(b.dataset.page)));
document.querySelectorAll("[data-page-jump]").forEach(b=>b.addEventListener("click",()=>setPage(b.dataset.pageJump)));
document.getElementById("refresh").addEventListener("click",async()=>{await refreshState();setPage(appState.page)});
refreshState().then(()=>setPage("home"));
