/* Claire Syntalion v19.89.8 Review Queue Surface */
(function(){
  const id='claire-review-queue-surface';
  const api='/system/review-queue/summary';
  function mount(){return document.getElementById('claire-runtime-propagation-surface')||document.querySelector('main')||document.body;}
  function ensure(){let s=document.getElementById(id); if(s) return s; s=document.createElement('section'); s.id=id; s.className='claire-review-queue-surface'; s.innerHTML=`<div class="review-queue-header"><div><div class="review-queue-kicker">REVIEW QUEUE INGESTION</div><h2>Governed Runtime Review Queue</h2></div><div class="review-queue-pill" data-review-queue-mode>Checking backend</div></div><div class="review-queue-grid"><div class="review-queue-card"><div class="review-queue-label">Pending</div><div class="review-queue-value" data-review-pending>-</div></div><div class="review-queue-card"><div class="review-queue-label">Acknowledged</div><div class="review-queue-value" data-review-acknowledged>-</div></div><div class="review-queue-card"><div class="review-queue-label">Rejected</div><div class="review-queue-value" data-review-rejected>-</div></div><div class="review-queue-card"><div class="review-queue-label">Latest State</div><div class="review-queue-value" data-review-latest>-</div></div></div><div class="review-queue-note" data-review-queue-note>Waiting for review queue truth.</div>`; const m=mount(); if(m===document.body){document.body.appendChild(s)}else{m.insertAdjacentElement('afterend',s)} return s;}
  async function refresh(){const s=ensure(); try{const r=await fetch(api,{cache:'no-store'}); if(!r.ok) throw new Error(api+' returned '+r.status); const p=await r.json(); const latest=p.latest_item||{}; const sum=latest.summary||{}; s.querySelector('[data-review-queue-mode]').textContent=p.queue_mode||'unknown'; s.querySelector('[data-review-pending]').textContent=p.pending_items??0; s.querySelector('[data-review-acknowledged]').textContent=p.acknowledged_items??0; s.querySelector('[data-review-rejected]').textContent=p.rejected_items??0; s.querySelector('[data-review-latest]').textContent=sum.terminal_state||'none'; s.querySelector('[data-review-queue-note]').textContent=latest.id?'Latest review item: '+latest.id:'Review queue is active. Runtime ingestion endpoint is ready.'; s.dataset.status='ok';}catch(e){s.dataset.status='error'; s.querySelector('[data-review-queue-mode]').textContent='Backend unavailable'; s.querySelector('[data-review-queue-note]').textContent='Review queue surface failed closed: '+e.message;}}
  window.ClaireReviewQueueSurface={version:'v19.89.8',refresh}; if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',refresh)}else{refresh()}
})();
