const state={runs:[],selected:null,files:[],active:null,timer:null,cursor:0};
const el=id=>document.getElementById(id); const fmt=(v,f='—')=>(v===undefined||v===null||v==='')?f:String(v);
function stat(id,msg,err=false){el(id).textContent=msg;el(id).style.color=err?'#f85149':'#8b949e'}
async function api(path,opt={}){const r=await fetch(path,opt);if(!r.ok)throw new Error(await r.text());const ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
function title(r){return r.category_name||r.sector||r.folder_name||r.run_id||'Claire run'}
async function loadTemplates(){try{const x=await api('/api/templates');const s=el('templateSelect');(x.templates||[]).forEach(t=>{const o=document.createElement('option');o.value=t.id;o.textContent=t.name;o.dataset.text=t.raw_input;s.appendChild(o)})}catch(e){}}
function renderRuns(){const list=el('runList');list.innerHTML='';el('runCount').textContent=state.runs.length;if(!state.runs.length){list.innerHTML='<div class="status">No runs found.</div>';return} state.runs.forEach(r=>{const d=document.createElement('div');d.className='runCard'+(state.selected&&state.selected.run_id===r.run_id?' active':'');d.innerHTML=`<strong>${fmt(title(r))}</strong><div class="meta">${fmt(r.created_at)}<br>Sector: ${fmt(r.sector)}<br>Decision: ${fmt(r.decision_classification)} · Files: ${fmt(r.written_file_count)}</div>`;d.onclick=()=>selectRun(r);list.appendChild(d)})}
function renderCards(r){const c=[['Run ID',r.run_id],['Output Folder',r.output_dir],['Domain',r.domain],['Sector',r.sector],['Category',r.category_name],['Decision',r.decision_classification],['Breakthrough',r.breakthrough_classification],['Portfolio Score',r.portfolio_score],['Export Level',r.export_package_level],['Export Score',r.export_package_score],['Documents',r.document_count],['Written Files',r.written_file_count]];el('summaryCards').innerHTML=c.map(([a,b])=>`<div class="card"><h3>${a}</h3><p>${fmt(b)}</p></div>`).join('')}
function renderFiles(files){state.files=files||[];el('filesValue').textContent=state.files.length||'—';el('fileList').innerHTML='';el('fileSelect').innerHTML='';state.files.forEach(f=>{const row=document.createElement('div');row.className='fileRow';row.innerHTML=`<div><strong>${f.filename}</strong><div class="muted">${fmt(f.format)} · ${fmt(f.size_bytes)} bytes</div></div><button>Preview</button><button>Open</button>`;row.children[1].onclick=()=>preview(f.filename);row.children[2].onclick=()=>window.open(`/api/runs/${encodeURIComponent(state.selected.run_id)}/files/${encodeURIComponent(f.filename)}?raw=1`,'_blank');el('fileList').appendChild(row);const o=document.createElement('option');o.value=f.filename;o.textContent=f.filename;el('fileSelect').appendChild(o)})}
async function selectRun(r){state.selected=r;renderRuns();el('emptyState').classList.add('hidden');el('detailState').classList.remove('hidden');el('selectedSector').textContent=fmt(r.sector);el('selectedTitle').textContent=title(r);el('selectedMeta').textContent=`${fmt(r.run_id)} · ${fmt(r.created_at)}`;el('decisionValue').textContent=fmt(r.decision_classification);el('exportValue').textContent=fmt(r.export_package_level);renderCards(r);el('rawBox').textContent=JSON.stringify(r,null,2);try{const x=await api(`/api/runs/${encodeURIComponent(r.run_id)}/files`);renderFiles(x.files||[]);const p=['run_summary.md','portfolio_binder.md','README.md'].find(n=>state.files.some(f=>f.filename===n));if(p)preview(p)}catch(e){el('previewBox').textContent=e.message}}
async function preview(name){if(!state.selected||!name)return;el('fileSelect').value=name;el('previewBox').textContent='Loading...';try{const x=await api(`/api/runs/${encodeURIComponent(state.selected.run_id)}/files/${encodeURIComponent(name)}?max_chars=120000`);el('previewBox').textContent=typeof x==='string'?x:(x.content||JSON.stringify(x,null,2));tab('preview')}catch(e){el('previewBox').textContent=e.message}}
function tab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));['summary','files','preview','raw'].forEach(t=>el(t+'Tab').classList.toggle('hidden',t!==name))}
async function loadRuns(id=null){stat('statusBox','Loading...');try{const x=await api('/api/runs');state.runs=x.runs||[];renderRuns();stat('statusBox',`Loaded ${state.runs.length} run(s).`);const target=id?state.runs.find(r=>r.run_id===id||r.folder_name===id):null;if(target)selectRun(target);else if(state.runs.length&&!state.selected)selectRun(state.runs[0])}catch(e){stat('statusBox','Failed: '+e.message,true)}}
async function rescan(){await api('/api/rescan',{method:'POST'});await loadRuns()}
function resetEvents(){state.cursor=0;el('eventList').innerHTML='';el('progressBar').style.width='0%';el('liveBadge').textContent='running'}
function addEvents(events){for(const ev of events){const d=document.createElement('div');d.className='event '+(ev.event_type==='complete'?'complete':ev.level==='error'?'error':'');d.innerHTML=`<strong>${fmt(ev.stage)} · ${fmt(ev.event_type)}</strong><div>${fmt(ev.message)}</div><div class="muted">${fmt(ev.timestamp)}</div>`;el('eventList').prepend(d);if(ev.progress!==undefined&&ev.progress!==null)el('progressBar').style.width=Math.max(0,Math.min(100,ev.progress))+'%'}}
async function poll(){if(!state.active)return;try{const x=await api(`/api/events/${state.active}?since=${state.cursor}`);addEvents(x.events||[]);state.cursor=x.event_count||state.cursor;if(x.status==='complete'||x.status==='error'){clearInterval(state.timer);state.timer=null;el('liveBadge').textContent=x.status;if(x.result){await loadRuns(x.result.run_id||x.result.folder_name)}stat('launchStatus',x.status==='complete'?'Run complete.':'Run failed: '+fmt(x.error),x.status==='error')}}catch(e){}}
async function launch(){const raw=el('rawInput').value.trim();if(!raw){stat('launchStatus','Add raw input before launching.',true);return}el('runBtn').disabled=true;resetEvents();try{const x=await api('/api/evaluate/async',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({raw_input:raw})});state.active=x.event_run_id;stat('launchStatus','Run started. Watching live events...');if(state.timer)clearInterval(state.timer);state.timer=setInterval(poll,900);poll()}catch(e){stat('launchStatus','Run failed to start: '+e.message,true)}finally{setTimeout(()=>{el('runBtn').disabled=false},1200)}}
document.addEventListener('DOMContentLoaded',()=>{loadTemplates();loadRuns();el('refreshBtn').onclick=()=>loadRuns();el('rescanBtn').onclick=rescan;el('runBtn').onclick=launch;el('clearBtn').onclick=()=>{el('rawInput').value='';stat('launchStatus','Ready.')};el('templateSelect').onchange=()=>{const o=el('templateSelect').selectedOptions[0];if(o&&o.dataset.text)el('rawInput').value=o.dataset.text};el('loadPreviewBtn').onclick=()=>preview(el('fileSelect').value);document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>tab(b.dataset.tab))});
