const state={runs:[],selected:null,files:[],last:null};
const el=id=>document.getElementById(id);
const fmt=(v,f='—')=>(v===undefined||v===null||v==='')?f:String(v);
function stat(id,msg,err=false){el(id).textContent=msg;el(id).style.color=err?'#f85149':'#8b949e'}
async function api(path,opt={}){const r=await fetch(path,opt);if(!r.ok)throw new Error(await r.text());const ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
function runTitle(r){return r.category_name||r.sector||r.folder_name||r.run_id||'Claire run'}
async function templates(){try{const x=await api('/api/templates');const s=el('templateSelect');(x.templates||[]).forEach(t=>{const o=document.createElement('option');o.value=t.id;o.textContent=t.name;o.dataset.text=t.raw_input;s.appendChild(o)})}catch(e){console.warn(e)}}
function renderRuns(){const list=el('runList');list.innerHTML='';el('runCount').textContent=state.runs.length;if(!state.runs.length){list.innerHTML='<div class="status">No runs found. Launch Claire or click Rescan.</div>';return}
 state.runs.forEach(r=>{const d=document.createElement('div');d.className='runCard'+(state.selected&&state.selected.run_id===r.run_id?' active':'');d.innerHTML=`<strong>${fmt(runTitle(r))}</strong><div class="meta">${fmt(r.created_at)}<br>Sector: ${fmt(r.sector)}<br>Decision: ${fmt(r.decision_classification)} · Files: ${fmt(r.written_file_count)}</div>`;d.onclick=()=>selectRun(r);list.appendChild(d)})}
function cardData(r){return [['Run ID',r.run_id],['Output Folder',r.output_dir],['Domain',r.domain],['Sector',r.sector],['Category',r.category_name],['Decision',r.decision_classification],['Breakthrough',r.breakthrough_classification],['Portfolio Score',r.portfolio_score],['Export Level',r.export_package_level],['Export Score',r.export_package_score],['Documents',r.document_count],['Written Files',r.written_file_count]]}
function renderCards(r){el('summaryCards').innerHTML=cardData(r).map(([a,b])=>`<div class="card"><h3>${a}</h3><p>${fmt(b)}</p></div>`).join('')}
function renderFiles(files){state.files=files||[];el('filesValue').textContent=state.files.length||'—';el('fileList').innerHTML='';el('fileSelect').innerHTML='';if(!state.files.length){el('fileList').innerHTML='<div class="status">No files found.</div>';return}
 state.files.forEach(f=>{const row=document.createElement('div');row.className='fileRow';row.innerHTML=`<div><strong>${f.filename}</strong><div class="fileMeta">${fmt(f.format)} · ${fmt(f.size_bytes)} bytes</div></div><button>Preview</button><button>Open</button>`;row.children[1].onclick=()=>preview(f.filename);row.children[2].onclick=()=>window.open(`/api/runs/${encodeURIComponent(state.selected.run_id)}/files/${encodeURIComponent(f.filename)}?raw=1`,'_blank');el('fileList').appendChild(row);const o=document.createElement('option');o.value=f.filename;o.textContent=f.filename;el('fileSelect').appendChild(o)})}
async function selectRun(r){state.selected=r;renderRuns();el('emptyState').classList.add('hidden');el('detailState').classList.remove('hidden');el('selectedSector').textContent=fmt(r.sector,'unknown sector');el('selectedTitle').textContent=runTitle(r);el('selectedMeta').textContent=`${fmt(r.run_id)} · ${fmt(r.created_at)}`;el('decisionValue').textContent=fmt(r.decision_classification);el('exportValue').textContent=fmt(r.export_package_level);renderCards(r);el('rawBox').textContent=JSON.stringify(r,null,2);try{const x=await api(`/api/runs/${encodeURIComponent(r.run_id)}/files`);renderFiles(x.files||[]);const p=['run_summary.md','portfolio_binder.md','README.md'].find(n=>state.files.some(f=>f.filename===n));if(p)preview(p)}catch(e){renderFiles([]);el('previewBox').textContent=e.message}}
async function preview(name){if(!state.selected||!name)return;el('fileSelect').value=name;el('previewBox').textContent='Loading preview...';try{const x=await api(`/api/runs/${encodeURIComponent(state.selected.run_id)}/files/${encodeURIComponent(name)}?max_chars=120000`);el('previewBox').textContent=typeof x==='string'?x:(x.content||JSON.stringify(x,null,2));tab('preview')}catch(e){el('previewBox').textContent=e.message}}
function tab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));['summary','files','preview','raw'].forEach(t=>el(t+'Tab').classList.toggle('hidden',t!==name))}
async function loadRuns(id=null){stat('statusBox','Loading run history...');try{const x=await api('/api/runs');state.runs=x.runs||[];renderRuns();stat('statusBox',`Loaded ${state.runs.length} run(s).`);const target=id?state.runs.find(r=>r.run_id===id||r.folder_name===id):null;if(target)selectRun(target);else if(state.runs.length&&!state.selected)selectRun(state.runs[0])}catch(e){stat('statusBox','Failed: '+e.message,true)}}
async function rescan(){stat('statusBox','Rescanning exports...');try{await api('/api/rescan',{method:'POST'});await loadRuns()}catch(e){stat('statusBox','Rescan failed: '+e.message,true)}}
async function launch(){const raw=el('rawInput').value.trim();if(!raw){stat('launchStatus','Add raw input before launching.',true);return}el('runBtn').disabled=true;stat('launchStatus','Claire is running. This may take a moment...');try{const x=await api('/api/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({raw_input:raw})});state.last=x;el('rawBox').textContent=JSON.stringify(x,null,2);const id=x.run_id||x.folder_name||(x.export_writer&&x.export_writer.folder_name);stat('launchStatus',`Run complete. Decision: ${fmt(x.decision_classification)}. Export: ${fmt(x.export_level)}.`);await loadRuns(id)}catch(e){stat('launchStatus','Run failed: '+e.message,true)}finally{el('runBtn').disabled=false}}
document.addEventListener('DOMContentLoaded',()=>{templates();loadRuns();el('refreshBtn').onclick=()=>loadRuns();el('rescanBtn').onclick=rescan;el('runBtn').onclick=launch;el('clearBtn').onclick=()=>{el('rawInput').value='';stat('launchStatus','Ready.')};el('templateSelect').onchange=()=>{const o=el('templateSelect').selectedOptions[0];if(o&&o.dataset.text)el('rawInput').value=o.dataset.text};el('loadPreviewBtn').onclick=()=>preview(el('fileSelect').value);document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>tab(b.dataset.tab))});
