"""
Defines WHO can authorize updates and WHAT they can touch

Claire v10.3.1 — Evolution & Update Governance
Generated by installer 5d394f869d1b on 2026-05-06

Content Specification:
  Authority levels: owner (Craig), system (Claire self-update), external (third-party). Per-authority: allowed_paths, denied_paths, requires_approval, max_change_scope. Methods: check_authority(source, target_path) — returns (authorized, reason). get_authority_for_path(path). Protected paths: lifecycle/, governance/, safety/, evolution/ require owner authority. Reads from data/update_governance/approvals/.
"""

class AuthorityMap:
    """
    Defines WHO can authorize updates and WHAT they can touch
    """

    def __init__(self):
        self._initialized = False

    def initialize(self):
        """Initialize the authority_map subsystem."""
        self._initialized = True
        return self

