"""
Evolution layer package init

Claire v10.3.1 — Evolution & Update Governance
Generated by installer 5d394f869d1b on 2026-05-06

Content Specification:
  Package marker. Exports: ProjectIdentity, MasterDocumentRegistry, VersionTimeline, TargetState, CapabilityRegistry, VerifiedStateStore, RegressionGuard, ForwardMotionPolicy, EvolutionMemory, EvolutionOrchestrator
"""

# Package marker. Exports: ProjectIdentity, MasterDocumentRegistry, VersionTimeline, TargetState, CapabilityRegistry, VerifiedStateStore, RegressionGuard, ForwardMotionPolicy, EvolutionMemory, EvolutionOrchestrator
