"""
Export Contract
==============
ACS2-Claire / Syntalion — v10.3.2

Defines the requirements for export packages. Every export/package
generated by Claire must satisfy this contract before delivery.

Export packages include portfolio binders, opportunity discovery packs,
technical feasibility reports, strategic positioning documents,
acquisition packages, and full pipeline outputs.
"""

import json
import hashlib
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple


class ExportContract:
    """Validates export package conformance."""

    VERSION = "10.3.2"

    PACKAGE_TYPES = [
        "portfolio_binder",
        "opportunity_discovery",
        "technical_feasibility",
        "strategic_positioning",
        "acquisition_package",
        "breakthrough_report",
        "full_pipeline_output",
        "proof_binder",
        "design_output",
        "technology_assessment",
    ]

    REQUIRED_PACKAGE_FIELDS = {
        "package_id": str,
        "package_type": str,
        "run_id": str,
        "company_name": str,
        "generated_at": str,
        "route_used": str,
        "terminal_state": str,
        "overall_score": (int, float),
        "sections": list,
        "evidence_summary": dict,
        "metadata": dict,
    }

    REQUIRED_SECTION_FIELDS = {
        "section_id": str,
        "title": str,
        "content": str,
        "section_type": str,
        "evidence_refs": list,
    }

    SECTION_TYPES = [
        "executive_summary",
        "thesis_statement",
        "market_analysis",
        "competitive_landscape",
        "financial_analysis",
        "risk_assessment",
        "technology_assessment",
        "strategic_recommendation",
        "acquisition_rationale",
        "evidence_appendix",
        "methodology",
        "data_sources",
    ]

    def __init__(self):
        self.errors = []
        self.warnings = []

    def validate(self, package: Dict[str, Any]) -> Tuple[bool, List[str], List[str]]:
        """Validate an export package against the contract."""
        self.errors = []
        self.warnings = []

        for field, expected_type in self.REQUIRED_PACKAGE_FIELDS.items():
            if field not in package:
                self.errors.append(f"Missing package field: {field}")
            elif not isinstance(package[field], expected_type):
                self.errors.append(f"Package field '{field}' type mismatch")

        pkg_type = package.get("package_type", "")
        if pkg_type and pkg_type not in self.PACKAGE_TYPES:
            self.warnings.append(f"Unknown package_type: {pkg_type}")

        sections = package.get("sections", [])
        if isinstance(sections, list):
            if len(sections) == 0:
                self.errors.append("Package must contain at least one section")
            for i, section in enumerate(sections):
                self._validate_section(i, section)

        evidence_summary = package.get("evidence_summary", {})
        if isinstance(evidence_summary, dict):
            if "total_sources" not in evidence_summary:
                self.warnings.append("evidence_summary missing total_sources")
            if "source_types" not in evidence_summary:
                self.warnings.append("evidence_summary missing source_types")

        return len(self.errors) == 0, self.errors.copy(), self.warnings.copy()

    def _validate_section(self, index: int, section: Dict[str, Any]):
        """Validate a single section within a package."""
        if not isinstance(section, dict):
            self.errors.append(f"Section {index} is not a dict")
            return

        for field in self.REQUIRED_SECTION_FIELDS:
            if field not in section:
                self.errors.append(f"Section {index} missing field: {field}")

        section_type = section.get("section_type", "")
        if section_type and section_type not in self.SECTION_TYPES:
            self.warnings.append(f"Section {index} unknown type: {section_type}")

        content = section.get("content", "")
        if isinstance(content, str) and len(content) < 10:
            self.warnings.append(f"Section {index} content suspiciously short")

    def generate_package_id(self, run_id: str, package_type: str) -> str:
        """Generate a deterministic package ID."""
        raw = f"{run_id}_{package_type}_{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"
        return f"pkg_{hashlib.sha256(raw.encode()).hexdigest()[:12]}"

    def get_required_sections(self, package_type: str) -> List[str]:
        """Return recommended section types for a package type."""
        section_map = {
            "portfolio_binder": [
                "executive_summary", "thesis_statement", "market_analysis",
                "competitive_landscape", "financial_analysis", "risk_assessment",
                "strategic_recommendation", "evidence_appendix",
            ],
            "acquisition_package": [
                "executive_summary", "thesis_statement", "market_analysis",
                "acquisition_rationale", "financial_analysis", "risk_assessment",
                "strategic_recommendation", "evidence_appendix",
            ],
            "breakthrough_report": [
                "executive_summary", "thesis_statement", "technology_assessment",
                "market_analysis", "strategic_recommendation", "evidence_appendix",
            ],
            "full_pipeline_output": self.SECTION_TYPES,
        }
        return section_map.get(package_type, ["executive_summary", "evidence_appendix"])

    def to_dict(self) -> Dict[str, Any]:
        """Serialize contract for audit/export."""
        return {
            "contract_type": "export_package",
            "version": self.VERSION,
            "package_types": self.PACKAGE_TYPES,
            "required_fields": list(self.REQUIRED_PACKAGE_FIELDS.keys()),
            "section_types": self.SECTION_TYPES,
        }
