"""
Contract Layer — Schema validation and data contracts.
Enforces input/output integrity at every pipeline boundary.
Mirrors the TypeScript ClaireIntent / ClaireResult from CLAIRE.md.
"""
import logging
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger("claire.contract")


@dataclass
class ExecutionContext:
    """Runtime context attached to every pipeline request."""
    session_id: str = ""
    user_id: str = "system"
    environment: str = "production"
    trace_id: str = ""

    def __post_init__(self):
        if not self.session_id:
            self.session_id = uuid.uuid4().hex[:8]
        if not self.trace_id:
            self.trace_id = uuid.uuid4().hex[:12]


@dataclass
class IntentMetadata:
    """Metadata envelope for every intent."""
    timestamp: str = ""
    source: str = "api"
    priority: str = "medium"

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.utcnow().isoformat() + "Z"

    def validate(self) -> List[str]:
        errors = []
        if self.source not in ("api", "ui", "cli"):
            errors.append(f"Invalid source: {self.source}")
        if self.priority not in ("low", "medium", "high"):
            errors.append(f"Invalid priority: {self.priority}")
        return errors


@dataclass
class ClaireIntent:
    """Input contract — validated request entering the pipeline."""
    id: str = ""
    user_id: str = "system"
    request_type: str = "evaluate"
    raw_input: str = ""
    mode: str = "deterministic"
    data: Dict[str, Any] = field(default_factory=dict)
    context: ExecutionContext = field(default_factory=ExecutionContext)
    metadata: IntentMetadata = field(default_factory=IntentMetadata)

    def __post_init__(self):
        if not self.id:
            self.id = f"intent-{uuid.uuid4().hex[:8]}"

    def validate(self) -> List[str]:
        errors = []
        if not self.raw_input:
            errors.append("raw_input is required")
        if self.mode not in ("deterministic", "connected", "hybrid"):
            errors.append(f"Invalid mode: {self.mode}")
        if self.request_type not in ("plan", "analyze", "evaluate", "construct"):
            errors.append(f"Invalid request_type: {self.request_type}")
        errors.extend(self.metadata.validate())
        return errors

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id, "user_id": self.user_id,
            "request_type": self.request_type, "raw_input": self.raw_input,
            "mode": self.mode, "source": self.metadata.source,
            "priority": self.metadata.priority,
            "timestamp": self.metadata.timestamp,
            "trace_id": self.context.trace_id,
        }


@dataclass
class PlanObject:
    """Execution plan generated by the Planner."""
    steps: List[str] = field(default_factory=list)
    strategy: str = "default"
    estimated_phases: int = 4


@dataclass
class SemanticRepresentation:
    """Semantic model output."""
    dimensions: Dict[str, float] = field(default_factory=dict)
    keywords: List[str] = field(default_factory=list)
    domain: str = "general"
    entities: List[str] = field(default_factory=list)
    confidence: float = 0.0


@dataclass
class ClaireResult:
    """Output contract — result produced by the pipeline."""
    intent_id: str = ""
    status: str = "success"
    plan: PlanObject = field(default_factory=PlanObject)
    data: Dict[str, Any] = field(default_factory=dict)
    semantic: SemanticRepresentation = field(default_factory=SemanticRepresentation)
    ready_for_syntalion: bool = False
    errors: List[str] = field(default_factory=list)
    scores: Dict[str, float] = field(default_factory=dict)
    acquirer_matches: List[Dict[str, Any]] = field(default_factory=list)
    compliance: Dict[str, Any] = field(default_factory=dict)
    mode: str = "deterministic"
    decision_classification: str = "UNKNOWN"
    breakthrough_classification: str = "UNKNOWN"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "intent_id": self.intent_id, "status": self.status,
            "ready_for_syntalion": self.ready_for_syntalion,
            "mode": self.mode,
            "scores": self.scores,
            "decision_classification": self.decision_classification,
            "breakthrough_classification": self.breakthrough_classification,
            "acquirer_matches": self.acquirer_matches,
            "compliance": self.compliance,
            "semantic": {
                "dimensions": self.semantic.dimensions,
                "keywords": self.semantic.keywords,
                "domain": self.semantic.domain,
                "confidence": self.semantic.confidence,
            },
            "plan": {"steps": self.plan.steps, "strategy": self.plan.strategy},
            "errors": self.errors, "data": self.data,
        }


class ContractValidator:
    """Validates inputs/outputs against CLAIRE data contracts."""

    MAX_INPUT = 50000
    MIN_INPUT = 3

    def validate_input(self, raw: Dict[str, Any]) -> Tuple[Optional[ClaireIntent], List[str]]:
        errors = []
        raw_input = raw.get("raw_input", "").strip()
        mode = raw.get("mode", "deterministic")
        source = raw.get("source", "api")
        priority = raw.get("priority", "medium")

        if not raw_input:
            errors.append("raw_input is required and cannot be empty")
            return None, errors
        if len(raw_input) < self.MIN_INPUT:
            errors.append(f"raw_input too short (min {self.MIN_INPUT} chars)")
        if len(raw_input) > self.MAX_INPUT:
            raw_input = raw_input[:self.MAX_INPUT]

        intent = ClaireIntent(
            raw_input=raw_input, mode=mode, data=raw,
            context=ExecutionContext(),
            metadata=IntentMetadata(source=source, priority=priority),
        )
        schema_errors = intent.validate()
        errors.extend(schema_errors)

        if errors:
            logger.warning(f"Contract validation errors: {errors}")
        else:
            logger.info(f"Contract validated: {intent.id} [{intent.mode}]")
        return intent, errors

    def validate_output(self, result: ClaireResult) -> List[str]:
        errors = []
        if not result.intent_id:
            errors.append("Result missing intent_id")
        if result.status not in ("success", "partial", "error"):
            errors.append(f"Invalid result status: {result.status}")
        return errors
