// Shared Claire dashboard formatters.
// Generated by Claire dashboard modernization installer.

export function formatScore(value) {
  if (value === null || value === undefined || Number.isNaN(Number(value))) return "—";
  const n = Number(value);
  return n <= 1 ? `${Math.round(n * 100)}%` : `${Math.round(n)}%`;
}

export function formatStatus(value) {
  return String(value || "unknown").replaceAll("_", " ");
}

export function pick(obj, keys = []) {
  const out = {};
  for (const key of keys) out[key] = obj?.[key];
  return out;
}
