from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List

STAGE = "S985-S1012"
VERSION = "v19.89.8-S985-S1012-active-cockpit-control-surface-force-mount"

BLOCKED_FLAGS: Dict[str, bool] = {'automatic_updates_enabled': False,
 'autonomous_crawling_enabled': False,
 'body_read_allowed': False,
 'browser_execution_enabled': False,
 'command_execution_enabled': False,
 'live_web_execution_enabled': False,
 'network_request_performed': False,
 'package_download_performed': False,
 'package_install_performed': False,
 'runtime_mutation_enabled': False,
 'runtime_truth_mutation_enabled': False,
 'search_provider_execution_enabled': False}

BUTTONS: List[Dict[str, Any]] = [{'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Verify source/search/body-read/source-ingestion readiness without external execution.',
  'execution_enabled': False,
  'key': 'run_readiness_audit',
  'label': 'Run readiness audit',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Show configured/missing provider readiness without making provider requests.',
  'execution_enabled': False,
  'key': 'inspect_providers',
  'label': 'Inspect providers',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'View allowlist, denylist, quarantine, and trust-tier constraints.',
  'execution_enabled': False,
  'key': 'open_source_policy',
  'label': 'Open source policy',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Build a governed query and source-scope plan without executing search.',
  'execution_enabled': False,
  'key': 'compile_search_plan',
  'label': 'Compile search plan',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Preview metadata-only search envelope while execution remains blocked.',
  'execution_enabled': False,
  'key': 'preview_metadata_search',
  'label': 'Preview metadata search',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Review metadata result fields and validation requirements.',
  'execution_enabled': False,
  'key': 'view_metadata_contract',
  'label': 'View metadata contract',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Inspect quarantined source/search evidence queue.',
  'execution_enabled': False,
  'key': 'open_quarantine_review',
  'label': 'Open quarantine review',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Normalize source/search data into reviewable cockpit cards.',
  'execution_enabled': False,
  'key': 'build_evidence_cards',
  'label': 'Build evidence cards',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Preview trust, recency, relevance, and citation-candidate scoring.',
  'execution_enabled': False,
  'key': 'score_source_confidence',
  'label': 'Score source confidence',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Show operator review/reject/promote-preview action descriptors.',
  'execution_enabled': False,
  'key': 'show_review_actions',
  'label': 'Show review actions',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Create a manual body-read request packet; body reads stay blocked.',
  'execution_enabled': False,
  'key': 'build_body_read_request',
  'label': 'Build body-read request',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Verify body-read risk/scope/sanitizer plan without reading page bodies.',
  'execution_enabled': False,
  'key': 'run_body_read_preflight',
  'label': 'Run body-read preflight',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Create source-ingestion draft from reviewed evidence only.',
  'execution_enabled': False,
  'key': 'draft_source_ingestion',
  'label': 'Draft source ingestion',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Show runtime-truth promotion preview; mutation remains blocked.',
  'execution_enabled': False,
  'key': 'preview_truth_promotion',
  'label': 'Preview truth promotion',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Check governed source/body-read/source-ingestion stop gate.',
  'execution_enabled': False,
  'key': 'verify_s900_gate',
  'label': 'Verify S900 gate',
  'operation_mode': 'preview_only',
  'requires_manual_review': True},
 {'blocked_reason': 'Operation buttons are cockpit controls only; execution gates remain blocked.',
  'description': 'Prove visible cockpit operation controls are mounted.',
  'execution_enabled': False,
  'key': 'verify_button_mount',
  'label': 'Verify button mount',
  'operation_mode': 'preview_only',
  'requires_manual_review': True}]


def get_cockpit_control_surface_payload() -> Dict[str, Any]:
    buttons = deepcopy(BUTTONS)
    actions = [
        {
            "key": button["key"],
            "label": button["label"],
            "status": "visible_preview_only",
            "execution_enabled": False,
            "manual_review_required": True,
            "blocked_reason": button["blocked_reason"],
        }
        for button in buttons
    ]
    return {
        "stage": STAGE,
        "version": VERSION,
        "status": "control_surface_ready",
        "readiness": "dashboard_operation_controls_visible",
        "backend_owned_truth": True,
        "dashboard_presentation_only": True,
        "control_surface": {
            "mounted_by": "active_html_response_injector_and_frontend_asset_patch",
            "button_count": len(buttons),
            "buttons": buttons,
            "groups": [
                {"key": "readiness", "label": "Readiness", "buttons": ["run_readiness_audit", "verify_s900_gate", "verify_button_mount"]},
                {"key": "source_search", "label": "Source / Search", "buttons": ["inspect_providers", "open_source_policy", "compile_search_plan", "preview_metadata_search", "view_metadata_contract"]},
                {"key": "evidence", "label": "Evidence Review", "buttons": ["open_quarantine_review", "build_evidence_cards", "score_source_confidence", "show_review_actions"]},
                {"key": "body_read", "label": "Body-Read Planning", "buttons": ["build_body_read_request", "run_body_read_preflight"]},
                {"key": "ingestion", "label": "Source Ingestion", "buttons": ["draft_source_ingestion", "preview_truth_promotion"]},
            ],
        },
        "actions": actions,
        "action_count": len(actions),
        "blocked_flags": deepcopy(BLOCKED_FLAGS),
        "dangerous_authority_preserved": all(value is False for value in BLOCKED_FLAGS.values()),
        "operator_message": "Visible cockpit controls are mounted. Buttons are preview/preflight only; no live web, body-read, mutation, package, or command authority is enabled.",
    }


def get_cockpit_control_surface_buttons() -> List[Dict[str, Any]]:
    return deepcopy(BUTTONS)


def preview_operation(operation_key: str) -> Dict[str, Any]:
    button = next((item for item in BUTTONS if item["key"] == operation_key), None)
    if button is None:
        return {
            "operation_key": operation_key,
            "status": "unknown_operation",
            "execution_enabled": False,
            "blocked_flags": deepcopy(BLOCKED_FLAGS),
            "message": "No matching governed operation button exists for this key.",
        }
    return {
        "operation_key": operation_key,
        "label": button["label"],
        "status": "preview_packet_ready",
        "execution_enabled": False,
        "manual_review_required": True,
        "network_request_performed": False,
        "body_read_performed": False,
        "runtime_mutation_performed": False,
        "command_execution_performed": False,
        "blocked_flags": deepcopy(BLOCKED_FLAGS),
        "message": "Preview only. The cockpit button exists, but all dangerous execution authority remains blocked.",
    }
