"""Acquirer Matching Engine v5.19 — strict sector-gated matching."""
from typing import Any, Dict, List, Optional

class AcquirerMatchingEngine:
    def __init__(self): self.candidates=self._library()
    def match(self, keywords: Optional[List[str]]=None, domain: str='general', market_gap: Optional[Dict[str,Any]]=None)->List[Dict[str,Any]]:
        keywords=keywords or []; market_gap=market_gap or {}; sector=market_gap.get('sector') or self._sector_from_domain(domain)
        groups={'climate_insurance':['climate_insurance','horizontal_ai_data'],'defense_autonomy':['defense_autonomy','horizontal_ai_data'],'healthcare_operations':['healthcare_operations','horizontal_ai_data'],'industrial_supply_chain':['industrial_supply_chain','horizontal_ai_data'],'energy_infrastructure':['energy_infrastructure','horizontal_ai_data'],'financial_market_intelligence':['financial_market_intelligence','horizontal_ai_data']}.get(sector,['general_intelligence','horizontal_ai_data'])
        cats=market_gap.get('acquirer_categories',[]); buyers=market_gap.get('buyer_segments',[]); pressure=market_gap.get('strategic_pressure',{}).get('score',0)
        q=set([k.lower() for k in keywords])|set(str(sector).replace('_',' ').split())|set(' '.join(cats).lower().split())|set(' '.join(buyers).lower().split())
        out=[]
        for group in groups:
            for c in self.candidates.get(group,[]):
                terms=set(str(c.get('name','')).lower().replace('/',' ').split())|set(str(c.get('sector','')).lower().replace('/',' ').split())
                for f in c.get('focus',[]): terms |= set(str(f).lower().replace('/',' ').split())
                matched=sorted(q&terms)
                ca=min(0.18,sum(0.055 for tag in c.get('category_tags',[]) if tag.lower() in ' '.join(cats).lower()))
                fa=min(0.18,len(matched)*0.018); sf=0.10 if group==sector else 0.04 if group=='horizontal_ai_data' else 0
                bf=min(0.12,sum(0.035 for tag in c.get('buyer_tags',[]) if tag.lower() in ' '.join(buyers).lower()))
                pb=min(0.04,float(pressure or 0)*0.04)
                score=round(min(0.98,0.58+ca+fa+sf+bf+pb+c.get('base_bonus',0)),4)
                out.append({'name':c['name'],'ticker':c.get('ticker','PRIVATE'),'type':'strategic','sector':c['sector'],'match_score':score,'matched_signals':matched,'rationale':self._rationale(ca,fa,sf,bf),'fit_dimensions':{'category_alignment':round(ca,4),'focus_alignment':round(fa,4),'sector_fit':round(sf,4),'buyer_segment_fit':round(bf,4),'strategic_pressure':round(pb,4)},'focus':c.get('focus',[])})
        return sorted(out,key=lambda x:x['match_score'],reverse=True)[:12]
    def _sector_from_domain(self,d): return {'insurance':'climate_insurance','finance':'financial_market_intelligence','healthcare':'healthcare_operations','industrial':'industrial_supply_chain','energy':'energy_infrastructure','technology':'general_intelligence'}.get(d,'general_intelligence')
    def _rationale(self,ca,fa,sf,bf):
        r=[]
        if ca:r.append('matches market-gap acquirer category')
        if fa:r.append('focus areas match opportunity requirements')
        if sf:r.append('candidate sector is allowed for detected sector')
        if bf:r.append('candidate likely sells into relevant buyer segment')
        return r or ['general strategic adjacency']
    def _c(self,group,name,ticker,sector,focus,tags,buyers=None,bonus=0): return {'group':group,'name':name,'ticker':ticker,'sector':sector,'focus':focus,'category_tags':tags,'buyer_tags':buyers or [],'base_bonus':bonus}
    def _library(self):
        c=self._c
        return {
        'climate_insurance':[c('climate_insurance','Verisk','VRSK','insurance analytics / risk data',['insurance analytics','catastrophe risk','property data','underwriting','climate risk'],['insurance analytics platforms','risk data providers'],['insurers','underwriting','property'],0.08),c('climate_insurance',"Moody's RMS",'MCO','catastrophe modeling / risk analytics',['catastrophe modeling','climate risk','insurance risk','exposure modeling'],['catastrophe modeling companies','risk data providers'],['reinsurers','catastrophe','underwriting'],0.08),c('climate_insurance','Swiss Re','SSREY','reinsurance / risk intelligence',['reinsurance','catastrophe risk','risk transfer','property exposure','climate risk'],['reinsurers'],['reinsurers','risk'],0.075),c('climate_insurance','Munich Re','MURGY','reinsurance / climate risk',['reinsurance','climate risk','catastrophe risk','risk transfer','insurance analytics'],['reinsurers','climate risk intelligence companies'],['reinsurers','insurers'],0.075),c('climate_insurance','Guidewire','GWRE','insurance core software',['insurance platform','underwriting workflow','claims','policy systems','analytics'],['insurance core software platforms'],['insurers','underwriting'],0.06),c('climate_insurance','Duck Creek Technologies','PRIVATE','insurance core software',['policy systems','insurance software','underwriting','claims','insurance workflows'],['insurance core software platforms'],['insurers'],0.055),c('climate_insurance','CoreLogic','CLGX','property data / risk analytics',['property risk','weather risk','hazard data','exposure analytics'],['risk data providers'],['property','insurers'],0.055),c('climate_insurance','Aon','AON','insurance brokerage / risk advisory',['risk transfer','insurance brokerage','climate risk','catastrophe analytics'],['insurance brokers','risk data providers'],['brokers','insurers'],0.05),c('climate_insurance','Marsh McLennan','MMC','risk advisory / insurance brokerage',['risk advisory','insurance brokerage','climate risk','risk transfer'],['insurance brokers','climate risk intelligence companies'],['brokers','insurers'],0.05)],
        'financial_market_intelligence':[c('financial_market_intelligence','Bloomberg','PRIVATE','financial data / market intelligence',['market data','financial analytics','risk signals','liquidity intelligence','institutional research'],['financial data platforms','market intelligence providers'],['asset','hedge','research'],0.08),c('financial_market_intelligence','S&P Global','SPGI','financial information / credit analytics',['credit analytics','market intelligence','risk data','sector analysis','financial benchmarks'],['financial data platforms','risk analytics companies'],['credit','risk'],0.08),c('financial_market_intelligence','MSCI','MSCI','investment analytics / risk',['portfolio analytics','risk modeling','factor signals','institutional investment tools'],['risk analytics companies','asset-management technology platforms'],['asset','risk'],0.075),c('financial_market_intelligence','FactSet','FDS','financial data / analytics',['financial data','analytics','portfolio intelligence','research workflow','market signals'],['financial data platforms'],['research','asset'],0.07),c('financial_market_intelligence','BlackRock Aladdin','BLK','asset management technology',['risk analytics','portfolio management','institutional capital','market risk','investment operations'],['asset-management technology platforms','risk analytics companies'],['asset','risk'],0.07)],
        'defense_autonomy':[c('defense_autonomy','Anduril','PRIVATE','defense technology',['autonomous defense','drones','mission systems','border security','AI'],['defense technology companies'],['defense','mission'],0.09),c('defense_autonomy','Lockheed Martin','LMT','defense prime',['autonomous systems','drones','sensor fusion','battlefield intelligence'],['defense primes','aerospace companies'],['defense'],0.08),c('defense_autonomy','Northrop Grumman','NOC','aerospace / defense',['aerospace','autonomous platforms','surveillance','command systems'],['defense primes','aerospace companies'],['defense'],0.075),c('defense_autonomy','RTX','RTX','defense systems',['sensors','missiles','defense systems','edge computing'],['defense primes'],['defense'],0.07),c('defense_autonomy','Palantir','PLTR','defense data intelligence',['battlefield intelligence','data fusion','decision systems','ontology'],['secure command platforms','defense technology companies'],['mission'],0.065)],
        'healthcare_operations':[c('healthcare_operations','Epic Systems','PRIVATE','healthcare software',['EHR','clinical workflow','health system operations','patient data'],['EHR ecosystem companies'],['health','hospital'],0.08),c('healthcare_operations','Oracle Health','ORCL','healthcare software / cloud',['EHR','hospital operations','healthcare analytics','cloud'],['EHR ecosystem companies','healthcare software platforms'],['hospital'],0.075),c('healthcare_operations','GE HealthCare','GEHC','healthcare operations technology',['capacity','hospital operations','clinical operations','workflow'],['healthcare analytics companies'],['hospital','capacity'],0.07),c('healthcare_operations','Philips','PHG','health technology',['clinical operations','patient flow','healthcare analytics'],['healthcare software platforms'],['patient','hospital'],0.06)],
        'industrial_supply_chain':[c('industrial_supply_chain','SAP','SAP','ERP / enterprise applications',['ERP','supply chain','procurement','planning','manufacturing'],['ERP platforms','supply-chain software companies'],['manufacturers','procurement'],0.08),c('industrial_supply_chain','Oracle','ORCL','ERP / supply-chain software',['ERP','supply chain planning','procurement','enterprise data'],['ERP platforms'],['manufacturers'],0.075),c('industrial_supply_chain','Siemens','SIEGY','industrial automation / software',['industrial automation','manufacturing','factory software','operations'],['industrial automation companies'],['manufacturers'],0.07),c('industrial_supply_chain','Kinaxis','KXSCF','supply-chain planning',['supply chain planning','shortage forecasting','resilience','planning'],['supply-chain software companies'],['supply-chain'],0.07)],
        'energy_infrastructure':[c('energy_infrastructure','Schneider Electric','SBGSY','energy management / automation',['grid operations','energy management','resilience','automation','infrastructure monitoring'],['utility software companies','energy management platforms'],['utilities'],0.075),c('energy_infrastructure','Siemens Energy','SMNEY','energy infrastructure',['grid infrastructure','transmission','energy systems','power demand','grid resilience'],['grid technology companies'],['grid','utilities'],0.075),c('energy_infrastructure','GE Vernova','GEV','energy technology',['grid software','power systems','utilities','transmission','energy resilience'],['grid technology companies'],['utilities'],0.065),c('energy_infrastructure','Itron','ITRI','utility intelligence',['utility data','metering','grid intelligence','demand forecasting','energy analytics'],['utility software companies'],['utilities'],0.06),c('energy_infrastructure','Hitachi Energy','HTHIY','grid technology',['grid automation','transmission','power infrastructure','grid stability'],['grid technology companies'],['grid'],0.055)],
        'horizontal_ai_data':[c('horizontal_ai_data','Palantir','PLTR','data intelligence',['ontology','data integration','decision intelligence','operational AI','enterprise analytics'],['data intelligence platforms'],['risk','operations'],0.025),c('horizontal_ai_data','Databricks','PRIVATE','data / AI platform',['data intelligence','lakehouse','AI','analytics','machine learning'],['enterprise AI platforms','data intelligence platforms'],['data'],0.02),c('horizontal_ai_data','Snowflake','SNOW','data cloud',['data cloud','analytics','governance','marketplace','AI data'],['data intelligence platforms'],['data'],0.015)],
        'general_intelligence':[c('general_intelligence','Palantir','PLTR','data intelligence',['ontology','decision intelligence','operational AI'],['data intelligence platforms'],['strategy'],0.035),c('general_intelligence','Databricks','PRIVATE','data / AI platform',['data intelligence','AI','analytics'],['enterprise AI platforms'],['data'],0.03)]}
