"""Business Model Engine v5.19 — sector-gated commercial logic."""
from typing import Any, Dict, List, Optional
import re
class BusinessModelEngine:
    def analyze(self,text:str,domain:str='general',keywords:Optional[List[str]]=None,market_gap:Optional[Dict[str,Any]]=None,trend_trajectory:Optional[Dict[str,Any]]=None,market_formation:Optional[Dict[str,Any]]=None,moat:Optional[Dict[str,Any]]=None,risk_regulation:Optional[Dict[str,Any]]=None,connector_sources:Optional[Dict[str,Any]]=None)->Dict[str,Any]:
        s=self._signals(text or '',keywords or [],domain,market_gap or {},trend_trajectory or {},market_formation or {},moat or {},risk_regulation or {},connector_sources or {})
        rev=self._revenue(s); price=self._pricing(s,rev); value=self._value(s); roi=self._roi(s); risk=self._risk(s); unit=self._unit(s,risk)
        return {'status':'success','domain':s['domain'],'sector':s['sector'],'revenue_model':rev,'pricing_model':price,'value_capture':value,'buyer_roi':roi,'go_to_market':self._gtm(s,market_gap or {}),'unit_economics':unit,'commercial_risk':risk,'commercialization_path':self._path(s,risk),'business_model_thesis':self._thesis(s,rev,value,roi,risk),'recommended_next_actions':self._actions(s,value,risk),'evidence_signals':s,'confidence':self._confidence(s)}
    def _signals(self,text,keywords,domain,mg,tr,mf,moat,rr,ext):
        c=f"{text.lower()} {' '.join(keywords).lower()}"; sector=mg.get('sector','general')
        def n(pats): return sum(1 for p in pats if re.search(p,c))
        return {'domain':self._dom(sector,domain),'sector':sector,'market_stage':self._text(mf,'market_stage','stage'),'formation_type':self._text(mf,'formation_type','type'),'pricing_term_count':n([r'subscription',r'license',r'enterprise',r'usage',r'api',r'module']), 'value_term_count':n([r'cost',r'savings',r'roi',r'risk reduction',r'losses',r'exposure',r'repricing']), 'enterprise_term_count':n([r'enterprise',r'workflow',r'integration',r'dashboard',r'platform']), 'sector_specific_term_count':self._sector_count(sector,c),'buyer_segment_count':len(mg.get('buyer_segments',[])),'acquirer_category_count':len(mg.get('acquirer_categories',[])),'market_growth':float(ext.get('market',{}).get('growth',0) or 0),'market_volatility':float(ext.get('market',{}).get('volatility',0) or 0),'financial_health':float(ext.get('financial',{}).get('health',0) or 0),'financial_risk':float(ext.get('financial',{}).get('risk',0) or 0),'market_gap_confidence':float(mg.get('confidence',0) or 0),'buyer_pull_score':self._get(mf,'buyer_pull','score'),'category_creation_score':self._get(mf,'category_creation_score','score'),'timing_pressure':self._get(tr,'timing_pressure','score'),'market_momentum':self._get(tr,'market_momentum','score'),'moat_score':self._get(moat,'moat_type','moat_score'),'copy_risk_score':self._get(moat,'copy_risk','score'),'risk_score':self._get(rr,'risk_profile','score'),'regulatory_exposure_score':self._get(rr,'regulation_profile','score'),'blocker_level':self._text(rr,'blocker_assessment','blocker_level') or 'unknown'}
    def _revenue(self,s):
        sec=s['sector']
        if sec=='climate_insurance': ranked=[('enterprise_subscription',0.46+s['buyer_pull_score']*.16+s['market_gap_confidence']*.10,'Best fit for insurers, reinsurers, and brokers using recurring climate-risk intelligence.'),('risk_data_product_subscription',0.42+s['category_creation_score']*.16+s['moat_score']*.12,'Climate exposure benchmarks and repricing signals can become premium data products.'),('underwriting_module_license',0.38+s['sector_specific_term_count']*.025+s['buyer_pull_score']*.10,'Underwriting teams can adopt targeted repricing and exposure modules.')]
        elif sec=='financial_market_intelligence': ranked=[('platform_license_plus_modules',0.44+s['category_creation_score']*.16+s['moat_score']*.10,'Financial signal products monetize through platform access and premium analytics modules.'),('enterprise_subscription',0.40+s['buyer_pull_score']*.14+s['market_gap_confidence']*.08,'Institutional buyers can subscribe to recurring market intelligence.'),('usage_based_intelligence_api',0.30+s['market_momentum']*.10,'Repeated signal calls can support API expansion.')]
        elif sec=='industrial_supply_chain': ranked=[('enterprise_subscription',0.44+s['buyer_pull_score']*.16+s['enterprise_term_count']*.02,'Recurring operational intelligence sold into enterprise manufacturing workflows.'),('platform_license_plus_modules',0.38+s['category_creation_score']*.16+s['moat_score']*.10,'Modules can expand across supplier risk, shortages, and procurement workflows.'),('pilot_to_enterprise_contract',0.36+s['risk_score']*.08,'Operational validation favors paid pilots before automation.')]
        else: ranked=[('enterprise_subscription',0.38+s['buyer_pull_score']*.15+s['market_gap_confidence']*.10,'Recurring intelligence platform access is the default commercial path.'),('platform_license_plus_modules',0.34+s['category_creation_score']*.14+s['moat_score']*.10,'Modular packaging supports expansion.'),('usage_based_intelligence_api',0.28+s['market_momentum']*.10,'Usage-based access can support later API expansion.')]
        rows=sorted([{'model':m,'fit_score':round(self._b(sc),4),'why':why} for m,sc,why in ranked],key=lambda x:x['fit_score'],reverse=True)
        return {'primary_model':rows[0]['model'],'secondary_models':[r['model'] for r in rows[1:3]],'ranked_models':rows,'revenue_logic':self._revenue_logic(rows[0]['model'],s)}
    def _pricing(self,s,rev):
        if s['sector']=='climate_insurance': pricing='annual enterprise subscription plus exposure-data modules'; metric='insured exposure, geographies, peril models, underwriting teams, and portfolio size'; pkg=self._climate_packages()
        elif s['sector']=='financial_market_intelligence': pricing='platform license plus premium signal modules'; metric='users, assets/workflows covered, data modules, API calls, and signal frequency'; pkg=self._finance_packages()
        elif s['sector']=='industrial_supply_chain': pricing='annual enterprise subscription'; metric='site count, supplier volume, modules, and workflow users'; pkg=self._industrial_packages()
        else: pricing='annual enterprise subscription'; metric='users, workflows, modules, and data integrations'; pkg=self._general_packages()
        power=self._b(.26+s['buyer_pull_score']*.18+s['moat_score']*.16+s['category_creation_score']*.12+s['sector_specific_term_count']*.012-s['risk_score']*.04)
        return {'recommended_pricing':pricing,'pricing_metric':metric,'pricing_power':self._level(power),'packaging':pkg}
    def _value(self,s):
        score=self._b(.24+s['buyer_pull_score']*.18+s['market_gap_confidence']*.14+s['category_creation_score']*.12+s['moat_score']*.14+s['sector_specific_term_count']*.018-s['risk_score']*.04)
        return {'strength':'strong' if score>=.78 else 'moderate' if score>=.60 else 'emerging','score':round(score,4),'value_drivers':self._drivers(s),'capture_mechanisms':self._capture(s)}
    def _roi(self,s):
        score=self._b(.22+s['buyer_pull_score']*.24+s['sector_specific_term_count']*.025+s['market_gap_confidence']*.12+s['timing_pressure']*.08)
        return {'roi_strength':'high' if score>=.78 else 'moderate' if score>=.60 else 'unproven','score':round(score,4),'economic_benefits':self._benefits(s),'proof_points_needed':self._proof(s)}
    def _gtm(self,s,mg):
        if s['blocker_level']=='conditional': motion='advisory pilot to enterprise expansion'
        elif s['sector']=='climate_insurance': motion='underwriting design-partner pilot to enterprise risk platform'
        elif s['sector']=='financial_market_intelligence': motion='category wedge with institutional design partners'
        elif s['sector']=='industrial_supply_chain': motion='direct enterprise sales with anchor-customer pilots'
        else: motion='focused pilot-led validation'
        return {'motion':motion,'first_customers':mg.get('buyer_segments',[])[:3],'sales_cycle':'medium_to_long' if s['blocker_level']=='conditional' else 'medium','procurement_complexity':self._burden(self._b(.22+s['risk_score']*.10+s['regulatory_exposure_score']*.08)),'entry_offer':self._entry(s),'expansion_motion':self._expansion(s)}
    def _risk(self,s):
        r=self._b(.18+s['risk_score']*.12+s['regulatory_exposure_score']*.08+s['financial_risk']*.08+(.08 if s['blocker_level']=='conditional' else 0)-s['buyer_pull_score']*.07-s['moat_score']*.04)
        return {'level':'high' if r>=.62 else 'moderate' if r>=.42 else 'low','score':round(r,4),'risk_factors':['conditional deployment blocker'] if s['blocker_level']=='conditional' else ['operational or compliance risk'] if s['risk_score']>=.45 else ['no major commercial risk surfaced']}
    def _unit(self,s,risk):
        gm=self._b(.54+s['moat_score']*.08+s['category_creation_score']*.05-s['risk_score']*.035); burden=self._b(.22+s['risk_score']*.08+s['regulatory_exposure_score']*.06+(.08 if s['blocker_level']=='conditional' else 0)); exp=self._b(.30+s['buyer_segment_count']*.03+s['category_creation_score']*.16+s['market_momentum']*.10+s['moat_score']*.08)
        return {'gross_margin_signal':self._level(gm),'implementation_burden':self._burden(burden),'expansion_potential':self._level(exp),'economics_interpretation':f"Gross-margin signal is {self._level(gm)['level']}; implementation burden is {self._burden(burden)['level']}; expansion potential is {self._level(exp)['level']}; commercial risk is {risk.get('level')}."}
    def _path(self,s,risk):
        if s['sector']=='climate_insurance': return [{'step':1,'name':'Underwriting pain validation','objective':'Confirm exposure, repricing, withdrawal, and risk-transfer pain.','exit_criteria':'Buyer validates climate-risk use case and economic value.'},{'step':2,'name':'Historical loss backtest','objective':'Validate against weather losses, exposure shifts, and repricing outcomes.','exit_criteria':'Backtest demonstrates decision-useful signal quality.'},{'step':3,'name':'Paid underwriting pilot','objective':'Deploy advisory-mode climate-risk intelligence into underwriting workflows.','exit_criteria':'Pilot demonstrates workflow fit and underwriting improvement.'},{'step':4,'name':'Enterprise risk platform conversion','objective':'Expand into subscription, exposure modules, and premium risk-data products.','exit_criteria':'Signed recurring contract with expansion modules.'}]
        return [{'step':1,'name':'Anchor pain validation','objective':'Confirm buyer pain, budget owner, and measurable ROI baseline.','exit_criteria':'Buyer validates urgency and economic value.'},{'step':2,'name':'Paid advisory pilot','objective':'Deploy in advisory/shadow mode with traceability and human review.','exit_criteria':'Pilot demonstrates accuracy, workflow fit, and risk controls.'},{'step':3,'name':'Enterprise platform conversion','objective':'Convert validated pilots to annual platform subscription or license.','exit_criteria':'Signed recurring contract.'},{'step':4,'name':'Module and data-loop expansion','objective':'Increase value through modules, data integrations, and intelligence loops.','exit_criteria':'Expansion revenue tied to proprietary data loops.'}]
    def _thesis(self,s,rev,value,roi,risk): return f"{s['sector'].replace('_',' ')} supports a {rev.get('primary_model')} business model. Value capture is {value.get('strength')} with buyer ROI rated {roi.get('roi_strength')}. Commercial risk is {risk.get('level')}."
    def _actions(self,s,value,risk):
        a=[{'action':'define anchor buyer and budget owner','purpose':'connect the opportunity to a specific economic buyer and procurement path','priority':'high'},{'action':'package advisory pilot with clear success metrics','purpose':'commercialize while constraints are validated','priority':'high'},{'action':'design expansion modules','purpose':'create a path from wedge to platform-level value capture','priority':'medium'}]
        if s['sector']=='climate_insurance': a.insert(1,{'action':'build ROI model around avoided loss exposure, repricing accuracy, and underwriting efficiency','purpose':'turn the climate-insurance value thesis into a quantifiable sales case','priority':'high'})
        elif s['sector']=='industrial_supply_chain': a.insert(1,{'action':'build ROI model around avoided shortages and reduced production disruption','purpose':'turn the value thesis into a quantifiable sales case','priority':'high'})
        elif s['sector']=='financial_market_intelligence': a.insert(1,{'action':'build ROI model around improved risk detection and signal value','purpose':'turn the signal-intelligence thesis into a quantifiable sales case','priority':'high'})
        if value.get('strength')!='strong': a.append({'action':'strengthen pricing proof','purpose':'validate willingness-to-pay before assuming strong value capture','priority':'medium'})
        return a
    def _revenue_logic(self,model,s): return 'Recurring subscription captures value from climate exposure intelligence, underwriting decision support, and premium risk-data modules.' if s['sector']=='climate_insurance' else 'Base platform access plus modules monetizes expanding intelligence layers.' if model=='platform_license_plus_modules' else 'Recurring enterprise subscription captures value from ongoing monitoring, forecasting, and workflow dependency.'
    def _drivers(self,s):
        return {'climate_insurance':['better underwriting precision','climate exposure visibility','repricing signal advantage','market withdrawal early warning','risk-transfer planning'],'financial_market_intelligence':['hidden signal detection','risk and liquidity visibility','institutional research workflow value','platform/category expansion potential'],'industrial_supply_chain':['avoided production disruption','reduced component shortage exposure','supplier-risk visibility','procurement prioritization'],'energy_infrastructure':['grid bottleneck visibility','asset-risk prioritization','resilience planning'],'healthcare_operations':['capacity optimization','staffing shortage visibility','patient-flow improvement']}.get(s['sector'],['validated buyer pain','workflow intelligence','platform expansion potential'])
    def _capture(self,s): return {'climate_insurance':['recurring platform access','underwriting modules','premium climate-risk data products','catastrophe scenario modules','portfolio exposure dashboards'],'financial_market_intelligence':['recurring platform access','premium signal modules','usage-based intelligence API','benchmark data products'],'industrial_supply_chain':['recurring platform access','paid workflow modules','implementation and integration fees','premium intelligence benchmarks']}.get(s['sector'],['recurring platform access','paid modules','implementation fees','premium benchmark intelligence'])
    def _benefits(self,s): return {'climate_insurance':['improved underwriting precision','better climate exposure pricing','earlier market-withdrawal warning','improved reinsurance and risk-transfer planning','reduced portfolio concentration risk'],'financial_market_intelligence':['earlier credit or liquidity stress detection','better portfolio risk visibility','improved research prioritization'],'industrial_supply_chain':['faster bottleneck detection','reduced shortage-related disruption','improved procurement prioritization']}.get(s['sector'],['faster risk detection','improved decision prioritization','better workflow intelligence'])
    def _proof(self,s): return {'climate_insurance':['historical weather-loss backtesting','repricing signal accuracy','underwriter workflow adoption','portfolio exposure lift','false-positive / false-negative analysis'],'financial_market_intelligence':['signal accuracy against historical regimes','false-positive / false-negative rates','workflow adoption','economic value of earlier risk detection'],'industrial_supply_chain':['forecast accuracy against historical disruptions','false-positive / false-negative rates','buyer workflow adoption','economic impact from avoided disruption','ERP / planning-system integration reliability']}.get(s['sector'],['forecast accuracy','false-positive / false-negative rates','workflow adoption','economic impact'])
    def _entry(self,s): return {'climate_insurance':'climate exposure and underwriting repricing pilot','financial_market_intelligence':'focused signal intelligence pilot','industrial_supply_chain':'shortage forecasting and supplier-risk pilot'}.get(s['sector'],'focused intelligence pilot')
    def _expansion(self,s): return {'climate_insurance':['underwriting repricing module','catastrophe scenario module','portfolio exposure dashboard','risk-transfer planning module','premium climate-risk benchmark data'],'financial_market_intelligence':['signal detection module','risk and liquidity models','portfolio workflow integration','premium benchmark intelligence'],'industrial_supply_chain':['supplier-risk graph','shortage forecasting module','bottleneck recommendation layer','procurement command dashboard','ERP / planning-system integrations']}.get(s['sector'],['workflow expansion','module expansion','data integration expansion','platform-wide deployment'])
    def _climate_packages(self): return [{'package':'Climate Risk Pilot','contents':['weather-loss backtesting','exposure concentration map','advisory underwriting signals','repricing baseline'],'purpose':'prove underwriting and portfolio-risk value'},{'package':'Insurance Risk Platform','contents':['continuous climate exposure monitoring','underwriting dashboard','catastrophe scenario layer','audit trail'],'purpose':'recurring insurance intelligence subscription'},{'package':'Expansion Modules','contents':['risk-transfer planning','market withdrawal prediction','premium exposure benchmarks','reinsurance portfolio analytics'],'purpose':'increase account value and deepen data moat'}]
    def _finance_packages(self): return [{'package':'Signal Pilot','contents':['historical regime backtesting','risk signal dashboard','advisory recommendations','ROI baseline'],'purpose':'prove signal value'},{'package':'Institutional Platform','contents':['continuous signal monitoring','risk models','workflow dashboard','audit trail'],'purpose':'recurring market intelligence subscription'},{'package':'Premium Modules','contents':['liquidity model','credit stress module','portfolio workflow integration','benchmark data'],'purpose':'expand account value'}]
    def _industrial_packages(self): return [{'package':'Pilot','contents':['limited data ingestion','historical backtesting','advisory recommendations','ROI baseline'],'purpose':'prove value and reduce deployment risk'},{'package':'Enterprise Platform','contents':['continuous monitoring','workflow dashboard','risk scoring','forecasting engine','audit trail'],'purpose':'recurring operational intelligence subscription'},{'package':'Expansion Modules','contents':['supplier-risk graph','shortage forecasting','bottleneck recommendations','ERP integrations','benchmark intelligence'],'purpose':'increase account value and deepen moat'}]
    def _general_packages(self): return [{'package':'Pilot','contents':['limited data ingestion','historical backtesting','advisory recommendations','ROI baseline'],'purpose':'prove value'},{'package':'Enterprise Platform','contents':['continuous monitoring','workflow dashboard','risk scoring','forecasting engine','audit trail'],'purpose':'recurring intelligence subscription'},{'package':'Expansion Modules','contents':['workflow modules','data integrations','benchmarks','API access'],'purpose':'expand value capture'}]
    def _sector_count(self,sector,c):
        pats={'climate_insurance':[r'insurance',r'reinsurance',r'underwriting',r'catastrophe',r'weather losses',r'exposure',r'repricing'], 'financial_market_intelligence':[r'credit',r'liquidity',r'portfolio',r'institutional'], 'industrial_supply_chain':[r'supplier',r'shortage',r'bottleneck',r'procurement',r'erp'], 'energy_infrastructure':[r'grid',r'utility',r'transmission'], 'healthcare_operations':[r'hospital',r'patient',r'capacity'], 'defense_autonomy':[r'defense',r'mission',r'drone']}.get(sector,[])
        return sum(1 for p in pats if re.search(p,c))
    def _b(self,v): return max(0,min(.96,v))
    def _level(self,score): return {'level':'strong' if score>=.72 else 'moderate' if score>=.52 else 'early','score':round(score,4)}
    def _burden(self,score): return {'level':'high' if score>=.65 else 'moderate' if score>=.42 else 'low','score':round(score,4)}
    def _confidence(self,s): return round(self._b(.24+s['market_gap_confidence']*.14+s['buyer_pull_score']*.16+s['category_creation_score']*.12+s['moat_score']*.12+s['market_momentum']*.08+min(.08,s['sector_specific_term_count']*.012)-s['risk_score']*.035),4)
    def _dom(self,sector,fallback): return {'climate_insurance':'insurance','defense_autonomy':'technology','healthcare_operations':'healthcare','industrial_supply_chain':'industrial','energy_infrastructure':'energy','financial_market_intelligence':'finance'}.get(sector,fallback or 'general')
    def _get(self,obj,*path):
        cur=obj
        for k in path:
            if not isinstance(cur,dict): return 0.0
            cur=cur.get(k,0.0)
        try:return float(cur or 0.0)
        except Exception:return 0.0
    def _text(self,obj,*path):
        cur=obj
        for k in path:
            if not isinstance(cur,dict): return ''
            cur=cur.get(k,'')
        return str(cur or '')
