const ClaireCockpit = (() => {
  const state = { generatedAt: null, endpointResults: {}, runtimeTruth: null, activeTab: "portfolio", diagnosticsVisible: false };
  const endpointGroups = {
    health: ["/health", "/"],
    dashboard: ["/dashboard/state", "/api/dashboard/state", "/dashboard/alignment/status"],
    runtime: ["/runtime/truth", "/runtime/state", "/api/runtime/state"],
    validation: ["/validation/authority", "/api/validation/authority"],
    internet: ["/internet/ops/dashboard", "/internet/operations/status", "/internet/operations/dashboard"],
    campaigns: ["/internet/campaigns/status", "/internet/campaigns"],
    sourceTrust: ["/internet/source-trust/status", "/internet/source-trust"],
    launch: ["/launch/regression-lock/status", "/api/launch/regression-lock"]
  };
  const apiBases = ["http://127.0.0.1:8000", "http://localhost:8000", ""];
  function $(id){ return document.getElementById(id); }
  function text(id, value){ const el=$(id); if(el) el.textContent = value == null || value === "" ? "Not loaded" : String(value); }
  function setClass(id, cls){ const el=$(id); if(el) el.className = cls; }
  function asObject(value){ return value && typeof value === "object" && !Array.isArray(value) ? value : {}; }
  function get(obj, paths, fallback=null){ for(const path of paths){ let cur=obj, ok=true; for(const part of path.split(".")){ if(cur && Object.prototype.hasOwnProperty.call(cur, part)) cur=cur[part]; else {ok=false; break;} } if(ok && cur !== undefined && cur !== null && cur !== "") return cur; } return fallback; }
  function truncate(value, limit=160){ const s=value == null ? "" : String(value); return s.length > limit ? s.slice(0, limit-1) + "..." : s; }
  function classifyPill(status){ const s=String(status||"").toLowerCase(); if(["ok","healthy","ready","complete","completed","passed","success","online"].some(x=>s.includes(x))) return "pill green"; if(["fail","error","blocked","invalid","missing"].some(x=>s.includes(x))) return "pill red"; if(["not","await","pending","warning","degraded","unverified"].some(x=>s.includes(x))) return "pill amber"; return "pill blue"; }
  async function fetchJson(url){ const controller=new AbortController(); const timeout=setTimeout(()=>controller.abort(),1300); try{ const response=await fetch(url,{cache:"no-store",signal:controller.signal}); clearTimeout(timeout); const ct=response.headers.get("content-type")||""; let body=null; if(ct.includes("application/json")) body=await response.json(); else body={text:truncate(await response.text(),500)}; return {ok:response.ok,status:response.status,url,body}; }catch(err){ clearTimeout(timeout); return {ok:false,status:"unreachable",url,error:String(err && err.message ? err.message : err)}; } }
  async function firstReachable(paths){ const attempts=[]; for(const base of apiBases){ for(const path of paths){ const url=path.startsWith("http") ? path : `${base}${path}`; const result=await fetchJson(url); attempts.push(result); if(result.ok) return {ok:true,selected:result,attempts}; } } return {ok:false,selected:null,attempts}; }
  async function refresh(){ state.generatedAt=new Date().toISOString(); const entries=await Promise.all(Object.entries(endpointGroups).map(async ([name, paths])=>[name, await firstReachable(paths)])); state.endpointResults=Object.fromEntries(entries); const candidates=[state.endpointResults.dashboard?.selected?.body,state.endpointResults.runtime?.selected?.body,state.endpointResults.validation?.selected?.body,state.endpointResults.internet?.selected?.body].filter(Boolean); state.runtimeTruth=candidates.find(obj=>obj && (obj.run_id || obj.route_selected || obj.route || obj.status || obj.runtime_truth || obj.dashboard_runtime_truth)) || null; render(); }
  function deriveSummary(){ const truth=asObject(state.runtimeTruth); const nested=asObject(truth.runtime_truth || truth.dashboard_runtime_truth || truth.core_run_output); const merged={...truth,...nested}; const route=get(merged,["route_selected","route","selected_route","active_route"],null); const terminal=get(merged,["terminal_state","status","completion_state"],null); const runId=get(merged,["run_id","mission_id","id"],null); const thesis=get(merged,["thesis.summary","thesis","strategic_thesis","trend_discovery.thesis"],null); const objective=get(merged,["objective","run_summary.objective","user_facing_result.objective","mission.objective"],null); const signal=get(merged,["signal_basis.summary","signal_basis","discovery.signal_state","trend_discovery.signal_state"],null); return {healthOk:!!state.endpointResults.health?.ok,internetOk:!!state.endpointResults.internet?.ok,sourceTrustOk:!!state.endpointResults.sourceTrust?.ok,route,terminal,runId,thesis,objective,signal,merged}; }
  function render(){ const s=deriveSummary(); text("proof-backend",s.healthOk?"Online":"Offline"); text("proof-runtime",state.runtimeTruth?"Loaded":"Not loaded"); text("proof-route",s.route||"Awaiting route"); text("proof-design",s.route && /design|solution|invention|breakthrough/i.test(String(s.route)) ? "Active route" : "Conditional"); text("proof-updates","Guarded"); text("side-mission",s.runId||"Not loaded"); text("side-route",s.route||"Awaiting output"); text("side-trust",state.endpointResults.validation?.ok?"Validation loaded":"Unverified"); text("side-internet",s.internetOk?"Reachable":"Not connected"); text("mission-title",s.runId?`Run ${s.runId}`:"No validated run loaded"); text("mission-summary",s.terminal?`Terminal/status: ${s.terminal}`:"Claire will show live runtime output when backend or runtime truth responds. No run data is invented."); text("brief-objective",truncate(s.objective||"No objective loaded",140)); text("brief-thesis",truncate(typeof s.thesis==="string"?s.thesis:JSON.stringify(s.thesis||"No thesis loaded"),180)); text("brief-signal",truncate(typeof s.signal==="string"?s.signal:JSON.stringify(s.signal||"Awaiting signal"),160)); text("brief-review",s.terminal?"Review loaded output":"Load or run Claire"); const missionPill=s.terminal || (state.runtimeTruth?"Runtime truth loaded":"Awaiting runtime truth"); text("mission-pill",missionPill); setClass("mission-pill",classifyPill(missionPill)); text("path-pill",s.route||"Awaiting route"); setClass("path-pill",classifyPill(s.route||"awaiting route")); text("internet-summary",s.internetOk?"Internet operations endpoint responded. Safe live use still depends on source governance, trust scoring, and update gates.":"Internet layers exist in the project, but the browser has not reached an internet operations endpoint."); text("internet-pill",s.internetOk?"Internet ops reachable":"Not verified in browser"); setClass("internet-pill",s.internetOk?"pill green":"pill amber"); highlightRoute(s.route); renderTab(); renderTrust(); renderDiagnostics(); }
  function highlightRoute(route){ const value=String(route||"").toLowerCase(); for(const id of ["route-portfolio","route-breakthrough","route-design","route-acquisition"]) $(id)?.classList.remove("active"); if(!value) return; if(value.includes("portfolio")) $("route-portfolio")?.classList.add("active"); if(value.includes("breakthrough")||value.includes("innovation")||value.includes("discovery")) $("route-breakthrough")?.classList.add("active"); if(value.includes("design")||value.includes("solution")||value.includes("invention")) $("route-design")?.classList.add("active"); if(value.includes("acquisition")||value.includes("package")) $("route-acquisition")?.classList.add("active"); }
  function escapeHtml(value){ return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;"); }
  function valueBlock(title,value,note){ const safe=value == null || value === "" ? "Not loaded" : (typeof value === "string" ? value : JSON.stringify(value,null,2)); return `<div class="list-item"><strong>${title}</strong><p>${escapeHtml(truncate(safe,520))}</p>${note?`<small>${escapeHtml(note)}</small>`:""}</div>`; }
  function renderTab(){ const s=deriveSummary(), m=s.merged||{}, tab=state.activeTab, target=$("tab-content"); if(!target) return; let html=""; if(tab==="portfolio"){ html=[valueBlock("Portfolio Output",get(m,["portfolio.summary","portfolio","portfolio_output"],null),"Default practical route when signals support portfolio action."),valueBlock("Trend / Thesis",get(m,["trend_discovery","thesis","strategic_thesis"],null),"Trend and thesis formation should precede route selection.")].join(""); } else if(tab==="breakthrough"){ html=[valueBlock("Breakthrough Classification",get(m,["breakthrough","breakthrough_classification","innovation_classification"],null),"Breakthrough/innovation is conditional, not forced."),valueBlock("Advancement Path",get(m,["advancement_path","path_selection","route_decision"],null),"Determines whether AutoDesign or another route is required.")].join(""); } else if(tab==="design"){ html=[valueBlock("AutoDesign",get(m,["autodesign","auto_design","auto_invention","solution"],null),"Required when discovery requires technology invention, system design, product design, or buildable solution generation."),valueBlock("Design Portal",get(m,["design_portal","design_output","blueprint"],null),"Should produce architecture, component map, stack, dependencies, blueprint, specs, and build plan."),valueBlock("Technology Intelligence",get(m,["technology_intelligence","technology","stack"],null),"Supports buildability, compatibility, deployment, and manufacturability decisions.")].join(""); } else if(tab==="acquisition"){ html=[valueBlock("Acquisition",get(m,["acquisition","acquirer_fit","acquisition_fit"],null),"Acquirer targeting and fit rationale."),valueBlock("Final Package",get(m,["final_package","package","exports"],null),"Final output for review, export, or buyer-facing package.")].join(""); } else if(tab==="actions"){ html=[valueBlock("Next Actions",get(m,["next_actions","actions","recommended_actions"],null),"Operator action list from runtime truth."),valueBlock("Failures / Blockers",get(m,["failures","blockers","errors"],null),"Blocked or insufficient-data states should be visible, not hidden.")].join(""); } target.innerHTML=html || valueBlock("No output",null,"No validated runtime output loaded for this tab."); }
  function renderTrust(){ const validation=state.endpointResults.validation?.selected?.body || state.endpointResults.dashboard?.selected?.body || {}; const source=state.endpointResults.sourceTrust?.selected?.body || {}; text("trust-summary",state.endpointResults.validation?.ok?"Validation authority endpoint responded.":"No validation authority response loaded yet."); text("source-trust-summary",state.endpointResults.sourceTrust?.ok?"Source trust endpoint responded.":"Source trust becomes actionable only after governed internet state is loaded."); if($("evidence-list")) $("evidence-list").innerHTML=valueBlock("Validation Snapshot",validation.status||validation.validation_status||validation,"Evidence and traceability should gate reuse."); if($("source-trust-list")) $("source-trust-list").innerHTML=valueBlock("Source Trust Snapshot",source.status||source.source_trust||source,"Adaptive source weighting and quarantine must stay governed."); text("memory-summary","Verified memory is a gate, not uncontrolled learning. It should only accept validated, evidence-backed outputs."); }
  function renderDiagnostics(){ const out=$("diagnostics-output"); if(!out) return; out.textContent=JSON.stringify({generatedAt:state.generatedAt,endpointResults:state.endpointResults,runtimeTruthLoaded:!!state.runtimeTruth,activeTab:state.activeTab,sourceOfTruth:"frontend/command_center/modern/index.html + claire_single_screen_operator.css/js",noFakeDataPolicy:true,routeReminder:"Discovery/breakthrough/innovation requiring invention must hand off to AutoDesign and Design Portal."},null,2); }
  function setTab(tab){ state.activeTab=tab; document.querySelectorAll(".tab").forEach(btn=>btn.classList.toggle("active",btn.dataset.tab===tab)); renderTab(); }
  function toggleDiagnostics(force){ state.diagnosticsVisible=typeof force==="boolean"?force:!state.diagnosticsVisible; $("diagnostics")?.classList.toggle("hidden",!state.diagnosticsVisible); if(state.diagnosticsVisible) $("diagnostics")?.scrollIntoView({behavior:"smooth",block:"start"}); }
  function runSearch(query){ const q=String(query||"").trim().toLowerCase(), results=$("search-results"), panels=document.querySelectorAll("[data-search]"); if(!q){ panels.forEach(p=>p.classList.remove("search-hidden")); if(results) results.textContent=""; return; } let matches=0; panels.forEach(panel=>{ const hit=`${panel.dataset.search||""} ${panel.textContent||""}`.toLowerCase().includes(q); panel.classList.toggle("search-hidden",!hit); if(hit) matches+=1; }); if(results) results.textContent=`${matches} cockpit sections matched "${query}".`; }
  function setupMic(){ const button=$("mic-button"), input=$("search-input"), SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition; if(!button||!input||!SpeechRecognition){ if(button) button.disabled=true; return; } const rec=new SpeechRecognition(); rec.continuous=false; rec.interimResults=false; rec.lang="en-US"; rec.onstart=()=>button.classList.add("listening"); rec.onend=()=>button.classList.remove("listening"); rec.onresult=event=>{ const transcript=event.results?.[0]?.[0]?.transcript||""; input.value=transcript; runSearch(transcript); }; button.addEventListener("click",()=>rec.start()); }
  function bind(){ $("refresh-button")?.addEventListener("click",refresh); $("diagnostics-button")?.addEventListener("click",()=>toggleDiagnostics()); $("copy-diagnostics")?.addEventListener("click",async()=>{ try{ await navigator.clipboard.writeText($("diagnostics-output")?.textContent||"{}"); }catch(_){} }); document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>setTab(btn.dataset.tab))); document.querySelectorAll(".nav-button").forEach(btn=>btn.addEventListener("click",()=>{ document.querySelectorAll(".nav-button").forEach(b=>b.classList.remove("active")); btn.classList.add("active"); const target=$(btn.dataset.section); if(target){ if(btn.dataset.section==="diagnostics") toggleDiagnostics(true); target.scrollIntoView({behavior:"smooth",block:"start"}); } })); $("search-input")?.addEventListener("input",event=>runSearch(event.target.value)); setupMic(); }
  return { bind, refresh };
})();
document.addEventListener("DOMContentLoaded",()=>{ ClaireCockpit.bind(); ClaireCockpit.refresh(); });
