from __future__ import annotations


CANONICAL_ROUTE_MODULES: list[str] = [
    "claire.api.dashboard_actions_registry_routes",
    "claire.api.dashboard_operator_console_contract",
    "claire.api.dashboard_status_visibility_aliases",
    "claire.api.governed_safety_routes",
    "claire.api.governed_connected_search",
    "claire.api.governed_cockpit_web_search_convergence_routes",
    "claire.api.governed_operator_experience_routes",
    "claire.api.governed_query_compiler_routes",
    "claire.api.governed_quarantine_evidence_routes",
    "claire.api.governed_provider_readiness_routes",
    "claire.api.governed_source_registry_routes",
    "claire.api.routes_design_portal_output",
    "claire.api.routes_dependency_chain_proof",
    "claire.api.routes_endpoint_reconciliation_compat",
    "claire.api.routes_endpoint_reconciliation_report",
    "claire.api.routes_industry_standard_endpoint_package",
    "claire.api.intelligence_answer_routes",
    "claire.api.operational_file_readiness",
    "claire.api.operator_action_click_result_surface",
    "claire.api.operator_cockpit_runtime",
    "claire.api.pipeline_activation_routes",
    "claire.api.portfolio_artifacts",
    "claire.api.routes_autodesign_handoff",
    "claire.api.routes_automatic_update_runner_gate",
    "claire.api.routes_buildability_validation",
    "claire.api.routes_continuous_runtime",
    "claire.api.routes_full_e2e_proof_pack",
    "claire.api.routes_governed_live_probe",
    "claire.api.routes_internet_readiness",
    "claire.api.routes_lifecycle_route_contracts",
    "claire.api.routes_emergence_causal_contracts",
    "claire.api.routes_operator_search_command",
    "claire.api.routes_open_web_update_governance",
    "claire.api.routes_operational_control_plane",
    "claire.api.routes_platform_endpoint_smoke_proof",
    "claire.api.routes_pipeline",
    "claire.api.routes_rollback_update_plan",
    "claire.api.routes_route_audit",
    "claire.api.routes_runtime_truth",
    "claire.api.routes_source_universes",
    "claire.api.routes_update_governance_regression_lock",
    "claire.api.routes_update_pack_staging",
    "claire.api.strategic_world_routes",
    "claire.api.technology_base_routes",
    "claire.api.safe_workflow_routes",
    "claire.canonical_cockpit_fetch_map_routes",
    "claire.routes.active_route_truth_routes",
]


LEGACY_ROUTE_MODULES: list[str] = [
    "claire.api.routes_dashboard_v4",
    "claire.api.routes_dashboard_v5",
    "claire.api.operator_dashboard_compat_routes",
    "claire.api.operator_router_include_adapter",
]
