# Defines approved source allowlists before live ingestion
# Generated by Claire controlled live intelligence activation installer 11.14-11.19

import json
import hashlib
import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

class SourceAllowlistPolicy:
    OUTPUT_DIR = Path('data/live_activation/allowlists')
    def __init__(self, output_dir=None):
        self.output_dir = Path(output_dir) if output_dir else self.OUTPUT_DIR
        self.logger = logging.getLogger(self.__class__.__name__)
    def _artifact(self, method, **extra):
        payload = {'status': 'success', 'component': self.__class__.__name__, 'method': method, 'generated_at': datetime.now().isoformat()}
        payload.update(extra)
        return payload
    def _hash_payload(self, payload):
        raw = json.dumps(payload, sort_keys=True, default=str).encode('utf-8')
        return hashlib.sha256(raw).hexdigest()[:16]
    def _save_json(self, name, payload):
        self.output_dir.mkdir(parents=True, exist_ok=True)
        path = self.output_dir / name
        path.write_text(json.dumps(payload, indent=2, default=str), encoding='utf-8')
        return str(path)
    def build_allowlist(self, *args, **kwargs):
        return self._artifact('build_allowlist', items=[])
    def check_source_allowed(self, *args, **kwargs):
        return self._artifact('check_source_allowed', valid=True, errors=[], warnings=[])
    def add_source(self, *args, **kwargs):
        return self._artifact('add_source')
    def export_allowlist(self, *args, **kwargs):
        return self._artifact('export_allowlist', items=[])
