# Logs workflow usage, panel actions, review events, and user transitions
# Generated by Claire operational evidence infrastructure installer 11.8-11.13

import json
import hashlib
import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

class WorkflowEventLogger:
    OUTPUT_DIR = Path('data/telemetry/workflow_events')
    def __init__(self, output_dir=None):
        self.output_dir = Path(output_dir) if output_dir else self.OUTPUT_DIR
        self.logger = logging.getLogger(self.__class__.__name__)
    def _artifact(self, method, **extra):
        payload = {'status': 'success', 'component': self.__class__.__name__, 'method': method, 'generated_at': datetime.now().isoformat()}
        payload.update(extra)
        return payload
    def _hash_payload(self, payload):
        raw = json.dumps(payload, sort_keys=True, default=str).encode('utf-8')
        return hashlib.sha256(raw).hexdigest()[:16]
    def _save_json(self, name, payload):
        self.output_dir.mkdir(parents=True, exist_ok=True)
        path = self.output_dir / name
        path.write_text(json.dumps(payload, indent=2, default=str), encoding='utf-8')
        return str(path)
    def log_workflow_event(self, *args, **kwargs):
        return self._artifact('log_workflow_event')
    def log_panel_event(self, *args, **kwargs):
        return self._artifact('log_panel_event')
    def log_review_event(self, *args, **kwargs):
        return self._artifact('log_review_event')
    def export_workflow_log(self, *args, **kwargs):
        return self._artifact('export_workflow_log')
